services:
  - type: web
    name: keyword-scanner
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y chromium-browser && \
      pip install -r requirements.txt
    startCommand: streamlit run Keyword_scan_web_scrap.py
    plan: free
